### ISSUE TITLE
Fix unmodifiable item

### ISSUE THREAD

**Issue by GuennisHueftgold** [GuennisHueftgold/ManniSpotter#24]
```
FATAL EXCEPTION: main
                  Process: com.semeshky.kvgspotter.osm, PID: 2868
                  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
                      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                   Caused by: java.lang.UnsupportedOperationException
                      at java.util.Collections$UnmodifiableList$1.set(Collections.java:1110)
                      at java.util.Collections.sort(Collections.java:1909)
                      at com.semeshky.kvgspotter.adapter.DepartureAdapter.setItems(DepartureAdapter.java:104)
                      at com.semeshky.kvgspotter.fragments.LiveMapDepartureFragment$4.onSuccess(LiveMapDepartureFragment.java:103)
                      at com.semeshky.kvgspotter.fragments.LiveMapDepartureFragment$4.onSuccess(LiveMapDepartureFragment.java:100)
                      at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
                      at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
```

**Comment by GuennisHueftgold** [comment]
Closed with #23
